# Default values for metabase - Generic version

# Global labels for all resources
global:
  service_name: metabase
  env_name: dev
  version: latest
  cluster_name: default
  labels:
    app.kubernetes.io/name: metabase
    app.kubernetes.io/instance: metabase
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: metabase
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "metabase"
    tags.datadoghq.com/version: "latest"

# Metabase configuration
metabase:
  image:
    repository: metabase/metabase
    tag: latest
  ports:
    http: 3000
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  persistence:
    enabled: false
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
  replicas: 1
  tolerations: []
  nodeSelector: {}
  ingress:
    url: metabase.example.com
  # Optional config section - if not provided, defaults will be used
  config:
    dbType: postgres
    dbPort: "5432"
    javaOpts: "-Xms512m -Xmx1024m"
    siteUrl: ""
    redirectAllRequestsToHttps: "false"
    customVars: {}

# Service configuration
service:
  type: ClusterIP
