apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.service_name }}-config
  labels:
    {{ toYaml .Values.global.labels | nindent 4 }}
data:
  {{- range .Values.metabase.configMapVars }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
  JAVA_OPTS: {{ .Values.metabase.javaOpts | quote }}
  MB_SITE_URL: https://{{ .Values.metabase.ingress.url }}/