apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-{{  .Values.global.service_name }}-sa
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-{{  .Values.global.service_name }}-auth
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
spec:
  method: kubernetes
  mount: kubernetes_{{ .Values.global.cluster_name }}
  kubernetes:
    role: vault-{{  .Values.global.service_name }}-role
    serviceAccount: vault-{{  .Values.global.service_name }}-sa
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-{{  .Values.global.service_name }}-secret
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
spec:
  vaultAuthRef: vault-{{  .Values.global.service_name }}-auth
  mount: secret
  type: kv-v2
  path: {{ .Values.global.service_name }}/server
  destination:
    name: {{ .Values.global.service_name }}-secret
    create: true
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-{{  .Values.global.service_name }}-db-secret
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
spec:
  vaultAuthRef: vault-{{  .Values.global.service_name }}-auth
  mount: secret
  type: kv-v2
  path: rds-apps/direct-connection
  destination:
    name: {{ .Values.global.service_name }}-db-secret
    create: true
  refreshAfter: 30s
