{{- if .Values.vault.connection.create }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ .Values.vault.connection.name }}
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
spec:
  address: {{ .Values.vault.connection.address }}
---
{{- end }}
{{- if .Values.vault.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metabase.vaultServiceAccountName" . }}
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
---
{{- end }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-{{  .Values.global.service_name }}-auth
  labels:
  {{ toYaml .Values.global.labels | nindent 4 }}
spec:
  method: kubernetes
  mount: {{ .Values.vault.authMount }}
  {{- if .Values.vault.connection.create }}
  vaultConnectionRef: {{ .Values.vault.connection.name }}
  {{- end }}
  kubernetes:
    role: vault-{{  .Values.global.service_name }}-role
    serviceAccount: {{ include "metabase.vaultServiceAccountName" . }}
    audiences:
      - vault
---
{{- range .Values.metabase.secretsVars }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-{{ .name }}
  labels:
  {{ toYaml $.Values.global.labels | nindent 4 }}
spec:
  vaultAuthRef: vault-{{ $.Values.global.service_name }}-auth
  mount: secret
  type: kv-v2
  path: {{ .vaultPath }}
  destination:
    name: {{ .name }}
    create: true
  refreshAfter: 30s
{{- end }}
