name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  github-release:
    uses: ZeroGachis/.github/.github/workflows/gh-release-please.yml@v4
    permissions:
      contents: write
      pull-requests: write
    with:
        major_and_minor_tags: false

  release:
    if: ${{ needs.github-release.outputs.release_created == 'true' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        if: ${{ needs.github-release.outputs.release_created == 'true' }}
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"